language: python

sudo: false

python:
  - "3.6"

env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py35-django18

  - TOX_ENV=py27-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django19

  - TOX_ENV=py27-django110
  - TOX_ENV=py34-django110
  - TOX_ENV=py35-django110

  - TOX_ENV=py27-django111
  - TOX_ENV=py34-django111
  - TOX_ENV=py35-django111
  - TOX_ENV=py36-django111

  - TOX_ENV=py34-djangomaster
  - TOX_ENV=py35-djangomaster
  - TOX_ENV=py36-djangomaster

cache:
  - pip

install:
  - pip install tox
  - pip install codecov

script:
  - tox -e $TOX_ENV

after_success:
  - codecov
